// <auto-generated />
using System;
using AM.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AM.Infrastructure.Migrations
{
    [DbContext(typeof(AMContext))]
    [Migration("20230108135646_m2")]
    partial class m2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AM.ApplicationCore.Domain.Cagnotte", b =>
                {
                    b.Property<int>("CagnotteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CagnotteId"), 1L, 1);

                    b.Property<DateTime>("DateLimite")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("MailProperty", true);

                    b.Property<int>("EntrepriseId")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("MailProperty", true);

                    b.Property<int>("SommeDemandée")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("MailProperty", true);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("CagnotteId");

                    b.HasIndex("EntrepriseId");

                    b.ToTable("Cagnottes");
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Entreprise", b =>
                {
                    b.Property<int>("EntrepriseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntrepriseId"), 1L, 1);

                    b.Property<string>("AdresseEntreprise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("MailProperty", true);

                    b.Property<string>("MailEntreprise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("MailProperty", true);

                    b.Property<string>("NomEntreprise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("MailProperty", true);

                    b.HasKey("EntrepriseId");

                    b.ToTable("Entreprises");
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Participant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipantId"), 1L, 1);

                    b.Property<string>("MailParticipant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("MailProperty", true);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("MailProperty", true);

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("MailProperty", true);

                    b.HasKey("ParticipantId");

                    b.ToTable("participants");
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Participation", b =>
                {
                    b.Property<int>("ParticipantFK")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<int>("CagnotteFK")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("Montant")
                        .HasColumnType("int");

                    b.HasKey("ParticipantFK", "CagnotteFK");

                    b.HasIndex("CagnotteFK");

                    b.ToTable("Participations");
                });

            modelBuilder.Entity("CagnotteParticipant", b =>
                {
                    b.Property<int>("CagnottesCagnotteId")
                        .HasColumnType("int");

                    b.Property<int>("participantsParticipantId")
                        .HasColumnType("int");

                    b.HasKey("CagnottesCagnotteId", "participantsParticipantId");

                    b.HasIndex("participantsParticipantId");

                    b.ToTable("Participation", (string)null);
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Cagnotte", b =>
                {
                    b.HasOne("AM.ApplicationCore.Domain.Entreprise", "Entreprise")
                        .WithMany("Cagnottes")
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Participation", b =>
                {
                    b.HasOne("AM.ApplicationCore.Domain.Cagnotte", "Cagnotte")
                        .WithMany("Participations")
                        .HasForeignKey("CagnotteFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AM.ApplicationCore.Domain.Participant", "Participant")
                        .WithMany("Participations")
                        .HasForeignKey("ParticipantFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cagnotte");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("CagnotteParticipant", b =>
                {
                    b.HasOne("AM.ApplicationCore.Domain.Cagnotte", null)
                        .WithMany()
                        .HasForeignKey("CagnottesCagnotteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AM.ApplicationCore.Domain.Participant", null)
                        .WithMany()
                        .HasForeignKey("participantsParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Cagnotte", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Entreprise", b =>
                {
                    b.Navigation("Cagnottes");
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Participant", b =>
                {
                    b.Navigation("Participations");
                });
#pragma warning restore 612, 618
        }
    }
}
